### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by eduardoalbuquerquedev** [eduardoalbuquerquedev/learn-vue#1]
- learn about vue js
 - [x] instalar o vue js
 - [x] desenvolver a primeira aplicação com vue js
 - [ ] subir arquivos para o repositório
